version: '3.4'
services:
  privatebin:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './config:/privatebin/cfg'
      - './data:/privatebin/data'
    ports:
      - '80:8888'
